INSERT INTO book (id,
                  title,
                  genre,
                  author,
                  publisher,
                  stock,
                  available_stock,
                  cover_image,
                  description,
                  featured)
VALUES ('f47ac10b-58cc-4372-a567-0e02b2c3d479',
        '1984',
        'Dystopian',
        'George Orwell',
        'Secker & Warburg',
        20,
        20,
        'https://m.media-amazon.com/images/I/61t0bwt1s3L._SL1000_.jpg',
        'A dystopian novel set in a totalitarian society ruled by Big Brother, where surveillance and propaganda dominate everyday life.',
        true),
       ('7c9e6679-7425-40de-944b-e07fc1f90ae7',
        'The Metamorphosis',
        'Fiction',
        'Franz Kafka',
        'Kurt Wolff Verlag',
        14,
        14,
        'https://m.media-amazon.com/images/I/61HuKUQYPjL._SL1280_.jpg',
        'A surreal novella about Gregor Samsa, who awakens one morning transformed into a giant insect, exploring themes of alienation and identity.',
        true),
       ('3fa85f64-5717-4562-b3fc-2c963f66afa6',
        'The Great Gatsby',
        'Classic',
        'F. Scott Fitzgerald',
        'Charles Scribner''s Sons',
        12,
        12,
        'https://m.media-amazon.com/images/I/81s3vOye7qL._SL1500_.jpg',
        'A story of wealth, love, and the American Dream set in the Roaring Twenties.',
        true),
       ('e2c569be-1b9b-4d77-b9b5-8f4b5fcb2aab',
        'Crime and Punishment',
        'Fiction',
        'Fyodor Dostoevsky',
        'The Russian Messenger',
        18,
        18,
        'https://m.media-amazon.com/images/I/61ZHmn6hd9L._SL1000_.jpg',
        'A psychological novel centered on Raskolnikov, a former student who commits a murder and struggles with guilt, morality, and redemption.',
        true),
       ('d290f1ee-6c54-4b01-90e6-d701748f0851',
        'The Lord of the Rings',
        'Fantasy',
        'J. R. R. Tolkien',
        'Allen & Unwin',
        25,
        25,
        'https://m.media-amazon.com/images/I/81nV6x2ey4L._SL1500_.jpg',
        'An epic fantasy tale of a quest to destroy a powerful ring and defeat the Dark Lord Sauron.',
        true),
       ('8fa14cdd-8a7f-4b8c-b3f1-75a3d8cbf4b8',
        'The Hobbit',
        'Fantasy',
        'J. R. R. Tolkien',
        'Allen & Unwin',
        20,
        20,
        'https://m.media-amazon.com/images/I/712cDO7d73L._SL1500_.jpg',
        'A fantasy adventure following Bilbo Baggins on a journey to reclaim a lost dwarven kingdom.',
        false),
       ('1c6b1478-2b6c-4a4f-87a4-74c73c86ec36',
        'Harry Potter and the Philosopher''s Stone',
        'Fantasy',
        'J. K. Rowling',
        'Bloomsbury',
        30,
        30,
        'https://m.media-amazon.com/images/I/81m9fP+LIPL._SL1500_.jpg',
        'The first book in the Harry Potter series, introducing a young wizard and the world of Hogwarts.',
        true),
       ('5b9f9e0d-7f1c-4f1d-a2de-bf4d3c1f9a82',
        'To Kill a Mockingbird',
        'Classic',
        'Harper Lee',
        'J. B. Lippincott & Co.',
        15,
        15,
        'https://m.media-amazon.com/images/I/81aY1lxk+9L._SL1500_.jpg',
        'A novel about racial injustice in the Deep South, seen through the eyes of young Scout Finch.',
        false),
       ('6fa459ea-ee8a-3ca4-894e-db77e160355e',
        'The Alchemist',
        'Adventure',
        'Paulo Coelho',
        'HarperTorch',
        22,
        22,
        'https://m.media-amazon.com/images/I/81ioPZFMeUL._SL1500_.jpg',
        'A philosophical novel about a shepherd named Santiago and his journey to discover his destiny.',
        false),
       ('16fd2706-8baf-433b-82eb-8c7fada847da',
        'Moby-Dick',
        'Adventure',
        'Herman Melville',
        'Richard Bentley',
        10,
        10,
        'https://m.media-amazon.com/images/I/81Baf0m5rBL._SL1500_.jpg',
        'The epic tale of Captain Ahab’s obsessive quest to hunt the white whale, Moby Dick.',
        false),
       ('123e4567-e89b-12d3-a456-426614174000',
        'Fahrenheit 451',
        'Dystopian',
        'Ray Bradbury',
        'Ballantine Books',
        18,
        18,
        'https://m.media-amazon.com/images/I/61sKsbPb5GL._SL1500_.jpg',
        'A novel about a future society where books are banned and "firemen" burn any that are found.',
        false);
